CumulativeEvents <- NULL
LowerActionLimit <- NULL
LowerWarningLimit <- NULL
ObservedMinusExpected <- NULL
SubjectIndex <- NULL
UpperActionLimit <- NULL
UpperWarningLimit <- NULL
USUBJID <- NULL    
Status <- NULL
p <- NULL
x <- NULL
y <- NULL
NObserved <- NULL
Upper <- NULL
Lower <- NULL
ExpectedRate <- NULL
HistoricalRate <- NULL
NObserved <- NULL
HistoricalRate <- NULL
ExpectedRate <- NULL
Ratio <- NULL
NHistorical <- NULL
LogRatio <- NULL
LogSD <- NULL
LowerLog <- NULL
UpperLog <- NULL
Upper <- NULL
qtl <- NULL
