CumulativeEvents <- NULL
LowerActionLimit <- NULL
LowerWarningLimit <- NULL
ObservedMinusExpected <- NULL
SubjectIndex <- NULL
UpperActionLimit <- NULL
UpperWarningLimit <- NULL
USUBJID <- NULL    
Status <- NULL
p <- NULL
x <- NULL
y <- NULL